server:
   port: 8097   
management:
  endpoints:
    web:
      exposure:
        include: "*"
        

spring:
  application:
      name: bloom-filter-redis-master
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://node4-devsvr.realsvr.cs-xc-idc1-area1.singhand.com:3306/CrawlerDBStore?useSSL=true
    username: cralwerdata
    password: cralwerdatastoreParch2016.

logging:
  level:
    org:
      springframework:
        security: info
